#!/bin/bash

AWS_ACCOUNT="000000000000"  # 379867926836
QUEUE_NAME="my-local-queue" # test-sqs-monitor
JOB_LIST="  test-sqs  another-job "
MAX_EXECUTE_MINUTES="300"
LOOP_INTERVAL_SECONDS="30"
FETCH_ATTEMPTS="3"
FALLBACK_RETRY="3"
FALLBACK_SLEEP_SECONDS="20  "

./kick.sh "$AWS_ACCOUNT" "$QUEUE_NAME" \
	"$JOB_LIST" \
	"$MAX_EXECUTE_MINUTES" \
	"$LOOP_INTERVAL_SECONDS" \
	"$FETCH_ATTEMPTS" \
	"$FALLBACK_RETRY" \
	"$FALLBACK_SLEEP_SECONDS" \
	>logs/out_test.log 2>logs/err_test.log
